[package]
name = "expresso-storage"
publish = false
version = "0.1.0"
edition = "2021"
description = "S3/MinIO abstraction layer"

[lib]
name = "expresso_storage"

[dependencies]
# Workspace deps
tracing = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
aws-sdk-s3 = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
