[package]
name = "expresso-crypto"
publish = false
version = "0.1.0"
edition = "2021"
description = "Cryptographic primitives, key management"

[lib]
name = "expresso_crypto"

[dependencies]
# Workspace deps
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
