[package]
name = "expresso-mail-parser"
publish = false
version = "0.1.0"
edition = "2021"
description = "MIME/email parsing and rendering"

[lib]
name = "expresso_mail_parser"

[dependencies]
# Workspace deps
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
